import Contador from "@/components/contador";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import House from "@/components/House";
import ThemeContextProvider from "@/context/ThemeContextProvider";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sistema Claro Oscuro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <ThemeContextProvider>
        <Header />
        <main>
          <House />
          <Contador />
        </main>
        <Footer />
      </ThemeContextProvider>
    </>
  );
}
